# This is a basic workflow that is manually triggered

name: 'Build and deploying the docker images to Azure Cloud Registry (ACR)'

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_SERVER_NAME }}
          username: ${{ secrets.AZURE_REPO_USERNAME }}
          password: ${{ secrets.AZURE_REPO_PASSWORD }}

      # Runs a single command using the runners shell
      - name: Build the User Interface (React)
        run: |
          docker build -t ${{ secrets.AZURE_SERVER_NAME }}/medical-drug-information_interface:${{ github.sha }} -f mdi_frontend/Dockerfile .
          docker push ${{ secrets.AZURE_SERVER_NAME }}/medical-drug-information_interface:${{ github.sha }}

      # Runs a set of commands using the runners shell
      - name: Build the Web server (python)
        run: |
          docker build -t ${{ secrets.AZURE_SERVER_NAME }}/medical-drug-information_webserver:${{ github.sha }} -f mdi_backend/Dockerfile .
          docker push ${{ secrets.AZURE_SERVER_NAME }}/medical-drug-information_webserver:${{ github.sha }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-container-image
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: azure/docker-login@v1
  #       with:
  #         login-server: ${{ secrets.AZURE_SERVER_NAME }}
  #         username: ${{ secrets.AZURE_REPO_USERNAME }}
  #         password: ${{ secrets.AZURE_REPO_PASSWORD }}

  #     - name: 'Deploy Container App'
  #       uses: Azure/cli@v1    
  #       with:
  #         inlineScript: |
  #           echo "Installing containerapp extension"
  #           az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
  #           echo "Started Deploying to containerapp (User Interface)"
  #           az containerapp update -n medical-information-ui -g gatech_related_apps -i ${{ secrets.AZURE_SERVER_NAME }}/medical-drug-information_interface:${{ github.sha }} --registry-login-server ${{ secrets.AZURE_SERVER_NAME }} --registry-username  ${{ secrets.AZURE_REPO_USERNAME }} --registry-password ${{ secrets.AZURE_REPO_PASSWORD }} --debug
  #           echo "Deployed to containerapp (User Interface)"
  #           echo "Started deploying to containerapp (webserver"
  #           az containerapp update -n medical-information-backend -g gatech_related_apps -i ${{ secrets.AZURE_SERVER_NAME }}/medical-drug-information_webserver:${{ github.sha }} --registry-login-server ${{ secrets.AZURE_SERVER_NAME }} --registry-username  ${{ secrets.AZURE_REPO_USERNAME }} --registry-password ${{ secrets.AZURE_REPO_PASSWORD }} --debug





