version: '3.7'
services:
  redis:
    image: bitnami/redis:latest
    container_name: nect-redis
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: default
    volumes:
      - redisvol:/bitnami/redis/data
  webserver:
    build: mdi_backend/
    container_name: mdi_backend
    ports:
      - "8000:5000"
    environment:
      - FDA_URL="https://api.fda.gov/drug/ndc.json"
      - REDIS_URL=redis
      - REDIS_PASSWORD=default
      - REDIS_PORT=6379
      - REDIS_DB=0
      - IN_DOCKER=YES
  interface:
    build: mdi_frontend/
    container_name: mdi_frontend
    ports:
      - "3000:80"
    depends_on:
      - webserver

volumes:
  redisvol:
    name: nect-redis-vol